### ISSUE TITLE
EventStoreGrainStorage read snap shot before events?

### ISSUE THREAD

**Issue by sarvasana** [hongliyu2002/Orleans.EventStore#2]
I stumbled upon your excellent contribution by accident and started reading code first, before I start playing with it.

While reading code I noticed EventStoreGrainStorage.ReadStateAsync<T> reads events to build grain state.
Would it make sense if EventStoreGrainStorage.ReadStateAsync<T> would attempt to load a snapshot from EventStoreDB first before reading events?

**Comment by hongliyu2002** [comment]
Event Sourcing based on EventStore DB is different from the built-in Orleans solution:

The built-in log-based approach does not actually involve snapshots. Every time the state is loaded, events are read and the state is rebuilt from version 0. The problem is that if there are 1,000,000 events, the state construction takes a long time.

That's why the EventStore-based solution is built on snapshots. It's worth noting that the term "snapshot" is different from "state." A snapshot refers to the state at a certain point in time. Therefore, you only need to record the state of the 999,998th event as a snapshot. Therefore, it reads from the snapshot first and then apply the last two events to recover the latest state.

**Comment by sarvasana** [comment]
Reading the code again I now see that Orleans.Persistence.EventStore only uses EventStore to persist the Grain state.
Therefore you can always read just the last state from the stream.
